# Generated by Django 5.2.6 on 2025-09-25 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("breed", models.CharField(max_length=255, verbose_name="breed")),
                (
                    "experience",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Cat's experience in years.",
                        validators=[django.core.validators.MaxValueValidator(30)],
                        verbose_name="experience",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cat's salary in USD.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="salary $",
                    ),
                ),
            ],
        ),
    ]
