# Generated by Django 5.2.6 on 2025-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sca", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Cat's image 🐈\u200d⬛.",
                null=True,
                upload_to="cats/",
                verbose_name="image",
            ),
        ),
    ]
