# Generated by Django 5.2.6 on 2025-09-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sca", "0003_alter_cat_options_alter_cat_image_mission_target_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time this object was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time this object was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time this object was created.",
                verbose_name="created at",
            ),
        ),
    ]
