# Generated by Django 5.2.6 on 2025-09-25 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sca", "0004_alter_mission_created_at_alter_note_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Breed",
                "verbose_name_plural": "Breeds",
            },
        ),
        migrations.AlterField(
            model_name="cat",
            name="experience",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Cat's experience in years.",
                validators=[django.core.validators.MaxValueValidator(30)],
                verbose_name="experience (yr.)",
            ),
        ),
        migrations.AlterField(
            model_name="cat",
            name="salary",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cat's salary in USD.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="salary ($)",
            ),
        ),
        migrations.AlterField(
            model_name="cat",
            name="breed",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sca.breed",
                verbose_name="breed",
            ),
        ),
    ]
