# Generated by Django 5.2.6 on 2025-09-25 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sca", "0005_breed_alter_cat_experience_alter_cat_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="breed",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sca.breed",
                verbose_name="breed",
            ),
            preserve_default=False,
        ),
    ]
